### ISSUE TITLE
Add generic Logging class

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/libDaisy#265]
Mentioned on the [Roadmap Forum post](https://forum.electro-smith.com/t/the-daisy-roadmap/805/8).

Should provide a simple way of starting up a USB or UART connection, and a print function.

This can be added to the DaisySeed so that there are generic `DaisySeed::Print` and `DaisySeed::PrintLine` functions (final names TBD).

**Comment by AXP** [comment]
### High level requirements

1. Should provide out-of-the box logging functionality over USB
2. Should initialize the required hardware
3. Should support disabling at compile time with a result of zero overhead (API calls should not produce any instructions)

### API requirements

1. API proposal:
```
void Print(const char* format, ...);     // print formatted string without appending end-of-line termination
void PrintLine(const char* format, ...); // print formatted string automatically appending end-of-line termination
void Start(UsbHandle::UsbPeriph device, bool wait_for_pc); // start the logging session. Device is either UsbHandle::FS_INTERNAL or UsbHandle::FS_EXTERNAL. The wait_for_pc flag blocks the execution until a key is pressed in the log terminal.
```
2. API calls should not lead to catastrophic failures if called (or not called) in wrong order/way. The application should still proceed with its core functionality.
3. There should be a way to configure end-of-line sequence ("\n", "\n\r", "\r\n", etc.). Supposedly with an internal #define 
4. If Print or PrintLine functions are executed before the Start() is invoked, the data should be buffered until the interface is initialized (useful for logging from global object constructors)
5. No dynamic memory allocation

### Open questions

1. All methods could be made static, should we make it a requirement?
2. It can be implemented as a separate class with static members only, so invocation in a random place might look like:
`daisy::Logger::Print(...);`
and that would work even if the Seed class is not instantiated in the current scope.
Otherwise (or in addition to the above) it can be pulled into the Seed class, so it becomes simply:
`seed.Print(...);`
3. PrintLine may unconditionally insert the end-of-line characters, or may analyze the string and only insert one if it's not there. It's pretty cheap since after formatting the string the position of the last character is already known.
4. If the Print* call is made while the USB is busy, it will block until it is free. Another approach would be to buffer data and retry on the next Print* call. But that could leave the very last message stuck forever in the buffer. Or we should use periodic tick to retry the transfer.
5. Should external USB port work? On my Pod it doesn't seem to out of the box. Should we support an option to print to both USB ports simultaneously? How about separately, with two instances of Logger?
6. Should we provide an option to alternatively (or in addition) output the log to PC via semihosting?
6. Location for the source code. Currently I'm developing it as hid/logger.h, next to the existing hid/usb.h
