### ISSUE TITLE
Patch SM gate out channel reversal

### ISSUE THREAD

**Issue by CorvusPrudens** [electro-smith/libDaisy#412]
In working with oopsy, I noticed that the `gate_out_1` and `gate_out_2` channels seemed reversed. I double checked all the schematics and the gen setup, but there wasn't a reversal error anywhere. It looks like this might be a similar problem to #268. 

I'm not sure if anyone else is experiencing this issue, but if so please comment!

**Comment by stephenhensley** [comment]
Not related to the channel swapping, just a schematic nuance from pin-swapping and stuff. Similar thing happened with some of the ADC channels.

the gateoutN net connected to the MCU have the opposite name as the net going to the pins. So they are swapped, but can be fixed by updating the GPIO assignment.
