### ISSUE TITLE
libDaisy doesn't compile with recent arm toolchain versions on linux

### ISSUE THREAD

**Issue by mfc** [electro-smith/libDaisy#538]
see full details: https://github.com/electro-smith/DaisyWiki/issues/33

**Comment by stephenhensley** [comment]
@mfc thanks for opening the issue!

We're aware of the compatibility issue, and it's the case with the most recent version of the compiler on all OSes.
Fixing it requires updating the entire STM32 HAL to a more recent, compatible version since libDaisy uses that extensively.

So while we do plan on getting this fixed, we don't have a timeline on exactly when it'll get done. 

We'll keep any further progress noted here!

**Comment by beserge** [comment]
Fixed via #582
