### ISSUE TITLE
Simple PWM interface / functionality

### ISSUE THREAD

**Issue by rafkhan** [electro-smith/libDaisy#594]
I am hoping for some type of PWM interface in the future, offering
- frequency
- duty cycle
- pin output selection

I'd imagine that such an interface be completely completely abstracts away stm32 timers... however, some notion of software vs. hardware timers might be useful.

**Comment by takumi-ogata** [comment]
Hi rafkhan, 

I'm really sorry that I overlooked this and for the delay in response. 

We actually have been working on hardware PWM, and we hope to release it in the near future.
https://github.com/electro-smith/libDaisy/pull/568 

Since we are working on it, I will close this for now. 
But when it's released and you find an issue, you're more than welcome to open a new one. Thank you so much!
