### ISSUE TITLE
RFC: utilize `daisy_init` as a macro for BSP boards

### ISSUE THREAD

**Issue by PaulBatchelor** [electro-smith/libDaisy#84]
In my head, this ties with #83.

As I'm beginning to grok the Daisy BSP architecture, I'm seeing that each BSP has their own init function. I would suggest having a macro `daisy_init` that is linked to the specific platform you want to use as a macro.

For instance, if I wanted to use the patch, I would include `dsy_patch_bsp.h`, which would have a line like `#define daisy_init daisy_patch_init`.

The big advantage of this is that it forces the user to consider their platform, otherwise the thing won't compile. It does take in a struct, which is a bit of a problem. I would say utilize opaque structs somehow or hide the data away as a global variable (this is what OpenGL does).

The bigger picture here is moving towards an interface that cleanly abstracts away some of the lower-level hardware details. The BSP already seems to be doing this to an extent, but this should make it so that all you need to do is change the BSP header file to compile it for any new board.

**Comment by stephenhensley** [comment]
At some point down the line we might be able to work this out. But for now, not all of the breakout boards have identical interfaces (they have a common base interface, but each has its own set of functions for ease-of-use). This would make it so that while some code would work across multiple breakouts, not all would.

Providing this macro would imply cross-compatibility in a way that isn't provided yet.
